name: Poetry Update

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  upgrade-dependencies:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: fuzzylabs/gha-poetry-update@v1
        with:
          python-version: 3.12
